/**
 * City Appearance table — per-building colors / typology / roofKind from open signals.
 * Generated by scripts/fetch-appearance.mjs (Sentinel-2 + Mapillary-or-prior + OSM).
 */

import { tryJSON } from '../data/dataSource.js';

export async function loadAppearance(url) {
  return tryJSON(url);
}

/** Fast lookup map: osmId(string) → record */
export function appearanceIndex(appearance) {
  if (!appearance?.buildings) return new Map();
  const map = new Map();
  for (const [k, v] of Object.entries(appearance.buildings)) {
    map.set(String(k), v);
    if (v.id != null) map.set(String(v.id), v);
  }
  return map;
}

export function rgbToHex(rgb) {
  if (!rgb || rgb.length < 3) return null;
  return ((rgb[0] & 255) << 16) + ((rgb[1] & 255) << 8) + (rgb[2] & 255);
}

/** Slight deterministic jitter so adjacent buildings don't look identical. */
export function jitterRgb(rgb, id, amount = 10) {
  if (!rgb) return rgb;
  let h = Math.abs(id | 0) * 2654435761;
  h ^= h >>> 16;
  const r = ((h >>> 0) / 4294967296) * 2 - 1;
  h = Math.abs((id | 0) * 1597334677);
  h ^= h >>> 16;
  const g = ((h >>> 0) / 4294967296) * 2 - 1;
  h = Math.abs((id | 0) * 3812015801);
  h ^= h >>> 16;
  const b = ((h >>> 0) / 4294967296) * 2 - 1;
  return [
    Math.max(0, Math.min(255, Math.round(rgb[0] + r * amount))),
    Math.max(0, Math.min(255, Math.round(rgb[1] + g * amount))),
    Math.max(0, Math.min(255, Math.round(rgb[2] + b * amount))),
  ];
}
